from fpdf import FPDF
from datetime import datetime
import os

class ReportService:
    def __init__(self):
        self.output_dir = "reports"
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_incident_report(self, incident: dict) -> str:
        pdf = FPDF()
        pdf.add_page()
        
        # Header
        pdf.set_font("Arial", "B", 20)
        pdf.cell(0, 10, "Sentinel AI - Incident Report", ln=True, align="C")
        pdf.ln(10)

        # Incident Details
        pdf.set_font("Arial", "B", 12)
        pdf.cell(40, 10, "Incident ID:", 0)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, incident["id"], ln=True)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(40, 10, "Date/Time:", 0)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, incident["timestamp"], ln=True)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(40, 10, "Severity:", 0)
        pdf.set_font("Arial", "", 12)
        pdf.set_text_color(255, 0, 0) if incident["severity"] == "Critical" else pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 10, incident["severity"], ln=True)
        pdf.set_text_color(0, 0, 0)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(40, 10, "Type:", 0)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, incident["hazard_type"], ln=True)

        pdf.set_font("Arial", "B", 12)
        pdf.cell(40, 10, "Location:", 0)
        pdf.set_font("Arial", "", 12)
        pdf.cell(0, 10, incident["location"], ln=True)

        pdf.ln(10)
        
        # Description
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Description:", ln=True)
        pdf.set_font("Arial", "", 12)
        pdf.multi_cell(0, 10, incident["description"])
        
        pdf.ln(10)

        # Actions Taken
        pdf.set_font("Arial", "B", 12)
        pdf.cell(0, 10, "Actions Log:", ln=True)
        pdf.set_font("Arial", "", 12)
        for action in incident.get("actions_taken", []):
            pdf.cell(0, 10, f"- {action['timestamp']}: {action['action']} by {action['user']}", ln=True)

        # Footer
        pdf.set_y(-15)
        pdf.set_font("Arial", "I", 8)
        pdf.cell(0, 10, f"Generated by Sentinel AI on {datetime.now().isoformat()}", 0, 0, "C")

        filename = f"{self.output_dir}/incident_{incident['id']}.pdf"
        pdf.output(filename)
        return filename
